version: '3.9'

services:
  database:
    image: postgres
    container_name: ignite_henrique
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=henrique_dev
      - POSTGRES_DB=ignite_henrique
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: ignite_app
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/user/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local